### ISSUE TITLE
linux/arm64/v8 support / possibilities

### ISSUE THREAD

**Issue by jplacht** [devforth/spa-to-http#8]
Hello and first: Thanks for this great way to serve SPA.

We're currently in the process of switching to a server on linux/arm64/v8 which is not supported by spa-to-http. Is there any way for us to change the Dockerfile to allow spa-to-http run on ARM hardware?

Many thanks
Jan

**Comment by ivictbor** [comment]
Hey @jplacht , thanks for your feedback, built  1.0.4, now all builds will have ARM support
![image](https://github.com/devforth/spa-to-http/assets/1838656/23a6645a-2f44-4c6f-aa83-c4c6e8438e9a)

(Actually it was done in https://github.com/devforth/spa-to-http/pull/7, we just forgot to rebuild)

**Comment by jplacht** [comment]
Fantastic, thank you - saved my day!
